version: '3.8'

services:
  app:
    image: dasa-genomics
    ports:
      - "5000:5000"
    volumes:
      - "./data:/app/data"
    environment:
      - DATA_FILE_PATH=/app/data/annotated_variants.tsv
