rule all:
    input:
        "data/annotated_variants.tsv"

rule annotate_variants:
    input:
        "data/NIST.vcf"
    output:
        "data/annotated_variants.tsv"
    shell:
        """
        python pipeline/scripts/annotate_variants.py {input} {output}
        """
